services:
  turtle_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: rob4-turtle
    container_name: ros2_humble_dev

    volumes:
      - /home/rg4444/rg4444-docker/Rob4-Gr444-Projekt/ros2_ws:/workspace
    working_dir: /workspace

    stdin_open: true
    tty: true

    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb

    environment:
      - ROS_DOMAIN_ID=30
      - TURTLEBOT3_MODEL=burger
