services:
  turtle_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: rob4-turtle
    container_name: ros2_humble_dev

    runtime: nvidia

    volumes:
      - /home/rg4444/rg4444-docker/Rob4-Gr444-Projekt/ros2_ws:/workspace
      - /dev:/dev
      - /run/udev:/run/udev:ro
      - /tpm/.X11-unix:/tpm/.X11-unix
    working_dir: /workspace
    stdin_open: true
    tty: true

    privileged: true
    network_mode: host
    pid: host
    ipc: host
    ulimits:
      rtprio: 99
      memlock: -1
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyACM0
      - /dev/ttyUSB0

    environment:
      - ROS_DOMAIN_ID=30
      - TURTLEBOT3_MODEL=burger
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - DISPLAY=:1
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
